# Default values for rbc-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

local:
  debug: true

replicaCount: 1

# DB config for app
# If no DB please replace with empty object {}
database:
  type: "mongodb"
  port: "27017"
  name: "rbc-auth"
  # Must be same as alias defined in chart
  # TODO - make this dynamic (within templates)
  serviceAlias: "rbc-auth-mongodb"

# Overriding DB values for mongodb
mongodb:
  auth:
    enabled: false
  # service:
  #   port: 27017
  #   nameOverride: "rbc-auth-mongodb"


image:
  repository: curioushuman/rbc-auth
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  # * NOTE: currently set to FALSE
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# * NOTE: at this point, if you want to use ingress you need to use this port
service:
  type: ClusterIP
  port: 3000
  portName: rbc-auth
  protocol: TCP

# OR define an optional ports array
# TODO - utilise in ingress and testconnection
# ports: [] # Use this if you want to remove this array
ports:
  - name: rbc-auth
    port: 3000
    targetPort: 3000
    protocol: TCP

livenessProbe:
  httpGet:
    path: /api/auth/hello
    port: rbc-auth
  failureThreshold: 1
  periodSeconds: 10

startupProbe:
  httpGet:
    path: /api/auth/hello
    port: rbc-auth
  failureThreshold: 30
  periodSeconds: 10

ingress:
  enabled: true
  # Leave this as blank
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: rbc.dev
      paths:
        - path: /api/auth/?(.*)
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
