apiVersion: skaffold/v2beta27
kind: Config
deploy:
  # kubeContext: "minikube"
  kubeContext: "docker-desktop"
  helm:
    # flags:
    #   install:
    #     [--debug]
    releases:
    - name: rbc
      version: ~0.1.15
      chartPath: k8s/rbc
      namespace: rbc
      createNamespace: true
      setValues:
        tags.rbc: false
    - name: rbc-auth
      version: ~0.2.1
      chartPath: k8s/subcharts/rbc-auth
      namespace: rbc
      artifactOverrides:
        image: curioushuman/rbc-auth
      imageStrategy:
        helm: {}
      setValues:
        global.umbrellaRelease: "rbc"
    - name: rbc-subscriptions
      version: ~0.2.1
      chartPath: k8s/subcharts/rbc-subscriptions
      namespace: rbc
      artifactOverrides:
        image: curioushuman/rbc-subscriptions
      imageStrategy:
        helm: {}
      setValues:
        global.umbrellaRelease: "rbc"
build:
  local:
    push: false
  artifacts:
    - image: curioushuman/rbc-auth
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile
        target: development
      sync:
        manual:
          - src: 'apps/auth/src/**/*.ts'
            dest: '/usr/src/app/'
          - src: 'libs/shared/**/*.ts'
            dest: '/usr/src/app/'
    - image: curioushuman/rbc-subscriptions
      context: .
      docker:
        dockerfile: apps/subscriptions/Dockerfile
        target: development
      sync:
        manual:
          - src: 'apps/subscriptions/src/**/*.ts'
            dest: '/usr/src/app/'
          - src: 'libs/shared/**/*.ts'
            dest: '/usr/src/app/'
