apiVersion: v2
name: rbc
description: An umbrella chart for the RbC ecosystem.
type: application
version: 0.1.15
dependencies:
  - name: rbc-auth
    repository: "file://../subcharts/rbc-auth"
    version: ~0.1.13
    tags:
      - auth
      - members
      - rbc
  # - name: rbc-subscriptions
  #   repository: "file://../subcharts/rbc-subscriptions"
  #   version: ~0.1.10
  #   tags:
  #     - subscriptions
  #     - members
  #     - rbc
  - name: nats
    repository: https://nats-io.github.io/k8s/helm/charts/
    version: ~0.14.2
    tags:
      - communication
      - nats

# TODO
# - Add labels component and part-of to subcharts
# - Disable the ingress for each microservice, in favour of a centralised one
#   - Move each individual ingress list into a _template
#   - Include an ingress template in the umbrella which pulls from the child templates
# - Add a service account for each microservice

# Problems I'm trying to solve / goals for structure
# - Keep things DRY
# - Ensure each microservice is self contained
# - Ensure each microservice can be e2e tested independently
# - Ensure each microservice can be deployed/upgraded independently
# - Allow some values to be shared across the ecosystem
# - Include/exclude specific chart aspects based on values

# Options
# I could structure this in a number of ways
# 1. Single subchart based on rbc-base, multiple aliases, override values
# 2. Multiple subcharts, with shared library chart

# Strategy
# - Shared library chart
#   - Push as much of the shared stuff to here (without going OTT)
# - Include a separate chart per service

# Useful links
# - https://github.com/cetic/helm-microservice
#   - A microservice template that seems to use this strategy
# - https://faun.pub/helm-conditions-and-tagging-for-umbrella-charts-f0ca9f6bb499
#   - A guide on how to use conditions and tagging in umbrella charts
#   - e.g. for individual or sub-group deployment of microservices
