apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbc-auth.fullname" . }}
  labels:
    {{- include "rbc-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.ports }}
    {{- range .Values.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
  {{- end }}
  selector:
    {{- include "rbc-auth.selectorLabels" . | nindent 4 }}
